### PR TITLE
License changed to LGPL, authors updated and NOTICE updated

### PR DESCRIPTION
**Pull request by jochenklar**
- License changed to LGPL v3 (as already stated in the package metadata).
- Authors updated
- Notice updated

@eFrane , @LucasJ , @vse , @MagdaN , @lundelius , @umut0 please agree to the license change.

### CODE REVIEW

**Comment by MagdaN** [comment]
I agree.

**Comment by vse** [comment]
I agree to the change.

**Comment by lundelius** [comment]
I agree.

Am 17/08/15 um 21:37 schrieb Volker Eichhorn:

> I agree to the change.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/webuildcity/wbc/pull/17#issuecomment-131938879.

## 

// Timo Lundelius
// timo@lundelius.com
// +49157 82901744
// Eidelstedter Weg 9, 20255 Hamburg, DE
// skype: timo.lundelius
// twitter: @timo_lundelius
// xing.com/profile/Timo_Lundelius
// linkedin.com/pub/timo-lundelius/27/92/8a7/

**Comment by userzimmermann** [comment]
Hi. Just a little hint ;)
The LGPLv3 text is just an extension to the GPLv3 text and should always be distributed together with the latter, as explained here:

http://www.gnu.org/licenses/gpl-howto.html

**Comment by eFrane** [comment]
:+1:

**Comment by LucasJ** [comment]
I agree.

**Comment by jochenklar** [comment]
@userzimmermann thanks for the info, I changed the files. If @umut0 agrees, I will merge.

**Comment by umut0** [comment]
i agree

**Pull request merged**
